### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ShrekID** [bakapear/igfeed#4]
(node:1195) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0
 at JSON.parse (<anonymous>)
    at /home/runner/dev/node_modules/despair/index.js:44:56
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.getMedia (/home/runner/dev/instagram.js:22:16)
    at async Timeout._onTimeout (/home/runner/dev/node_modules/corrin/index.js:12:21)

**Comment by bakapear** [comment]
Yeah it seems like some Instagram API-points do not work reliably anymore. I'm trying to find ways that do not require authentification right now

**Comment by ShrekID** [comment]
we need session id for it i guess.
